version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8006:8006"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
